# Generated by Django 4.1.13 on 2023-12-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='avisos',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[[0, 'Sugerencias'], [1, 'Ayuda'], [2, 'Reportes'], [3, 'Más']]),
        ),
    ]
