# Generated by Django 4.1.13 on 2023-12-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Prescio',
            new_name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='descricpcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
    ]
