# Generated by Django 4.1.13 on 2023-12-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_prescio_producto_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=20)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'hola'], [2, 'sugerencia'], [3, 'muertee']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
    ]
