# Generated by Django 4.1.13 on 2023-12-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contactos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactoS',
            new_name='Contacto',
        ),
    ]
