# Generated by Django 4.1.13 on 2024-03-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_ucompartido', models.IntegerField()),
                ('id_archivo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'ㅤ  Seleccionar'), (1, 'ㅤ  Sugerencias'), (2, 'ㅤ  Ayuda'), (3, 'ㅤ  Reportes'), (4, 'ㅤ  Otros')], default=0)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_archivo', models.CharField(max_length=255)),
                ('hora_analizado', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
