# Generated by Django 4.1.13 on 2024-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[(0, 'ㅤSeleccionar'), (1, 'ㅤSugerencias'), (2, 'ㅤAyuda'), (3, 'ㅤReportes'), (4, 'ㅤOtros')], default=0)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fichero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('id_archivo', models.CharField(max_length=255)),
            ],
        ),
    ]
