# Generated by Django 5.0.3 on 2024-03-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichero',
            name='id_usuario',
            field=models.IntegerField(),
        ),
    ]
