# Generated by Django 4.1.13 on 2024-03-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fichero_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_ucompartido', models.IntegerField()),
                ('id_archivo', models.CharField(max_length=255)),
            ],
        ),
    ]
