# Generated by Django 4.1.13 on 2024-03-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compartidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.IntegerField(choices=[(0, 'ㅤ  Seleccionar'), (1, 'ㅤ  Sugerencias'), (2, 'ㅤ  Ayuda'), (3, 'ㅤ  Reportes'), (4, 'ㅤ  Otros')], default=0),
        ),
    ]
