# Generated by Django 4.1.13 on 2024-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichero',
            name='hora_analizado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
