# Generated by Django 5.0.3 on 2024-03-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_fichero_hora_analizado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compartidos',
            new_name='Compartido',
        ),
    ]
