version: "3.8"

services:
  
  mongo-db:
    image: mongo:4.4
    environment:
      MONGO_INITDB_DATABASE: Proyecto
      MONGO_INITDB_ROOT_USERNAME: pasix
      MONGO_INITDB_ROOT_PASSWORD: 20Logicalis21
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb_data_container:
