version: "3.8"

services:
  
  mongo-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: demodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongo-compose-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Proyecto
      MYSQL_USER: pasix
      MYSQL_PASSWORD: pasix
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  mongo-compose-network:
    driver: bridge

volumes:
  mongodb_data_container: